Correct typing issue with null/string by keeping potential for field to be null within object, but when using as array property (i.e. meme[varCanBeNull], which will yield something like:
src/git-identity/git-identity.ts:146:102 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{}'.

146       str += "\n\n" + new Identity(keys[i], identities[keys[i]].username, identities[keys[i]].email, identities[keys[i]].gpgKey).toString();
                                                                                                         ~~~~~~~~~~~~~~~~~~~

src/git-identity/identity.ts:19:26 - error TS2538: Type 'null' cannot be used as an index type.

19     if(this.gpgKey) JSON[this.name].gpgKey = this.gpgKey;

, make sure to ultimately force it into a string by making it '' if falsy (i.e. this.name || '')