Hmmm... npm installing "@types/chalk" doesn't seem to have helped, the note given:
=================

npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!

=================

The only error left that we are attempting to tackle:

=================

src/cli/cli.ts:114:23 - error TS2339: Property 'green' does not exist on type 'typeof import("/home/luiserebii/github/git-identity/node_modules/chalk/types/index")'.

114     console.log(chalk.green(figlet.textSync('Git Identity', { font: 'Ghost' })))

=================